### PR TITLE
Add more default secret patterns

### PR DESCRIPTION
**Pull request by ddgenome**
Add secret patterns for GitHub tokens, URLs with passwords, Instagram,
Foursquare, Slack, GCP, and Heroku. Add word boundaries to secret
patterns, as appropriate. Add tests.

### CODE REVIEW

**Comment by ddgenome** [comment]
I thought I disabled the staging secret scanner for scan.test.ts, but it is still running somewhere.

**Review by cdupuis — APPROVED** [review]
You may now go in peace. Many thanks ...

**Comment by ddgenome** [comment]
I'd let this run on our stuff for a bit before release to make sure the new patterns do not produce too many false positives.

**Comment by cdupuis** [comment]
> I'd let this run on our stuff for a bit before release to make sure the new patterns do not produce too many false positives.

Sounds good. I can cut a release next week.

**Pull request merged**
